### PR TITLE
add parts of high level interface

### PR DESCRIPTION
**Pull request by KristofferC**
This implements some of the high level interface:

Implemented:
- `Ax_mul_Bx` for matrices and vectors
- `norm`
- `vecdot`
- `scale`, `scale!`

CC @kshyatt @denizyuret

### CODE REVIEW

**Comment by kshyatt** [comment]
Nice! I'll take a closer look later today :)

**Comment by KristofferC** [comment]
Since I used some of the code in Julia Base I should probably put some copyright notice.

**Comment by KristofferC** [comment]
However, this repo is under the Julia "flag" so maybe it is not needed.. @StefanKarpinski, do you have any opinion?

**Comment by StefanKarpinski** [comment]
Since the license remains MIT, I don't think it's necessary.

**Comment by KristofferC** [comment]
Bumpie bompie

**Pull request merged**
